import type { NextPage } from 'next';
import Head from 'next/head';

/**
 * index.tsx 에서 서버관련된 커스텀 설정을 한다.
 * @returns
 */
const Home: NextPage = () => {
  //#region render
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
  //#endregion
};

export default Home;
